### ISSUE TITLE
Audio error handling test

### ISSUE THREAD

**Issue by bockstaller** [Trashtunes/trashtun.es#12]
```
songtitle: Donald Trump
spotify_uri: 009jCZOeESiUSyuQkUFNaG
audio_comment: https://upload.wikimedia.org/wikipedia/commons/0/0c/04.Iv.Allegro.ogg
captions: |
  Die Orange dankt aber, das geht nicht ohne passende musikalische Untermalung.  
```

**Comment by bockstaller** [comment]
```
songtitle: Donald Trump
spotify_uri: 009jCZOeESiUSyuQkUFNaG
audio_comment: https://upload.wikimedia.org/wikipedia/commons/0/0c/04.Iv.Allegro.ogg
captions: |
  Die Orange dankt aber, das geht nicht ohne passende musikalische Untermalung.  
```

**Comment by bockstaller** [comment]
# Error

            Encountered an error while handling your magnificent voice sensually describing trash:

            ```
            File is not a zip file
            ```

            I hope this error is helpful.
            You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.

            And as always, remember to  **REUSE**, **REDUCE** and **RAVE**

**Comment by bockstaller** [comment]
```

songtitle: Donald Trump
spotify_uri: 009jCZOeESiUSyuQkUFNaG
audio_comment: https://upload.wikimedia.org/wikipedia/commons/0/0c/04.Iv.Allegro.ogg
captions: |
  Die Orange dankt ab aber, das geht nicht ohne passende musikalische Untermalung.  
```

**Comment by bockstaller** [comment]
<pre><code>        # Error

        Encountered an error while handling your magnificent voice sensually describing trash:

        ```
        File is not a zip file
        ```

        I hope this error is helpful.
        You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.

        And as always, remember to  **REUSE**, **REDUCE** and **RAVE**
</code></pre>

**Comment by bockstaller** [comment]
<pre><code>        # Error

        Encountered an error while handling your magnificent voice sensually describing trash:

        ```
        File is not a zip file
        ```

        I hope this error is helpful.
        You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.

        And as always, remember to  **REUSE**, **REDUCE** and **RAVE**
</code></pre>

**Comment by bockstaller** [comment]
<h1>Error</h1>
<pre><code>        Encountered an error while handling your magnificent voice sensually describing trash:

        ```
        File is not a zip file
        ```

        I hope this error is helpful.
        You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.

        And as always, remember to  **REUSE**, **REDUCE** and **RAVE**
</code></pre>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your magnificent voice sensually describing trash:</p>
<pre><code>File is not a zip file
</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your magnificent voice sensually describing trash:</p>
<pre><code>File is not a zip file

Traceback (most recent call last):
  File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 74, in upload_audio_to_s3
    zip = zipfile.ZipFile(BytesIO(r.content))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>

**Comment by bockstaller** [comment]
<p>(' <strong>Error</strong>', 'Encountered an error while handling your trash:', ' ', '<code>', 'list index out of range', ' ', ' ', 'Traceback (most recent call last): File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 66, in take_trash_from_github trashyaml = trashdefinitions[0][1] IndexError: list index out of range ', '</code>', ' ', 'I hope this error is helpful.', 'You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.', ' ', 'And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong>')</p>

**Comment by bockstaller** [comment]
<p><strong>Error</strong>Encountered an error while handling your trash: ```list index out of range  Traceback (most recent call last):<br>
File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 66, in take_trash_from_github<br>
trashyaml = trashdefinitions[0][1]<br>
IndexError: list index out of range</p>
<div class="highlight highlight-source-assembly"><pre></pre></div>

**Comment by bockstaller** [comment]
<p><strong>Error</strong>Encountered an error while handling your trash: ```list index out of range  Traceback (most recent call last):<br>
File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 72, in take_trash_from_github<br>
trashyaml = trashdefinitions[0][1]<br>
IndexError: list index out of range</p>
<div class="highlight highlight-source-assembly"><pre></pre></div>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your trash:</p>
<pre><code>list index out of range
 
 
Traceback (most recent call last):
  File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 72, in take_trash_from_github
    trashyaml = trashdefinitions[0][1]
IndexError: list index out of range

</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your trash:</p>
<pre><code>list index out of range
 
 
Traceback (most recent call last):
  File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 72, in take_trash_from_github
    trashyaml = trashdefinitions[0][1]
IndexError: list index out of range

</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your trash:</p>
<pre><code>list index out of range
 
 
Traceback (most recent call last):
  File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 74, in take_trash_from_github
    trashyaml = trashdefinitions[0][1]
IndexError: list index out of range

</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your trash:</p>
<pre><code>list index out of range
 
 
Traceback (most recent call last):
  File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 76, in take_trash_from_github
    trashyaml = trashdefinitions[0][1]
IndexError: list index out of range

</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your trash:</p>
<pre><code>list index out of range
 
 
Traceback (most recent call last):
  File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 76, in take_trash_from_github
    trashyaml = trashdefinitions[0][1]
IndexError: list index out of range

</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>

**Comment by bockstaller** [comment]
<p><strong>Error</strong><br>
Encountered an error while handling your trash:</p>
<pre><code>File is not a zip file
 
 
Traceback (most recent call last):
  File "/Users/bockstaller/Documents/code/trashtun.es/trashman.py", line 102, in upload_audio_to_s3
    zip = zipfile.ZipFile(BytesIO(r.content))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

</code></pre>
<p>I hope this error is helpful.<br>
You can retry by appending a new comment to this issue with the same formatting or by editing the issue content.</p>
<p>And as always, remember to  <strong>REUSE</strong>, <strong>REDUCE</strong> and <strong>RAVE</strong></p>
